name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t dashboard:$(date +%s) .
    - name: Docker Login
      env: 
        DOCKER_USER: ${secrets.DOCKER_USERNAME}
        DOCKER_PASSWORD: ${secrets.DOCKER_PASSWORD}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Push to DockerHub
      run: docker push sshiv6353/dashboard
      
      
